//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

//user
export const SET_DATA_AFTER_RESPONSE = 'SET_DATA_AFTER_RESPONSE';
export const CHECK_VERIFIED_USER_EXISTS = 'CHECK_VERIFIED_USER_EXISTS';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_TUYA_REQUEST = 'LOGIN_TUYA_REQUEST';
export const LOGIN_TUYA_FAILED = 'LOGIN_TUYA_FAILED';
export const LOGIN_TUYA_SUCCESS = 'LOGIN_TUYA_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_REMOVE_TEMP_DATA = 'LOGIN_REMOVE_TEMP_DATA';
export const LOGOUT = 'LOGOUT';

export const RENEW_TUYA_SESSION_AND_RELOAD_THE_APP = 'RENEW_TUYA_SESSION_AND_RELOAD_THE_APP';

export const REMOVE_LISTENERS_ON_LOGOUT_REQUEST = 'REMOVE_LISTENERS_ON_LOGOUT_REQUEST';
export const REMOVE_LISTENERS_ON_LOGOUT_SUCCESS = 'REMOVE_LISTENERS_ON_LOGOUT_SUCCESS';
