export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_ACCEPTED_LANGUAGE = 'SET_ACCEPTED_LANGUAGE';
export const CHANGE_ACCEPTED_LANGUAGE = 'CHANGE_ACCEPTED_LANGUAGE';
export const CHANGE_ACCEPTED_LANGUAGE_SUCCESS = 'CHANGE_ACCEPTED_LANGUAGE_SUCCESS';
export const CHANGE_ACCEPTED_LANGUAGE_FAILED = 'CHANGE_ACCEPTED_LANGUAGE_FAILED';

export const GET_COUNTRIES_AND_CHANGE_ACCEPTED_LANGUAGE =
  'GET_COUNTRIES_AND_CHANGE_ACCEPTED_LANGUAGE';
export const GET_COUNTRY_BY_ISO = 'GET_COUNTRY_BY_ISO';
export const GET_COUNTRY_BY_ISO_SUCCESS = 'GET_COUNTRY_BY_ISO_SUCCESS';
export const GET_COUNTRY_BY_ISO_FAILED = 'GET_COUNTRY_BY_ISO_FAILED';
export const GET_COUNTRIES_DATA = 'GET_COUNTRIES_DATA';
export const GET_COUNTRIES_DATA_SUCCESS = 'GET_COUNTRIES_DATA_SUCCESS';
export const GET_COUNTRIES_DATA_FAILED = 'GET_COUNTRIES_DATA_FAILED';
