export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAILED = 'GET_ADDRESS_FAILED';
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS';
