// localIpAddress
export const SET_LOCAL_IP_TO_STORE = 'SET_LOCAL_IP_TO_STORE';

export const DETECT_LOCATION_BY_IP = 'DETECT_LOCATION_BY_IP';
export const DETECT_LOCATION_BY_IP_SUCCESS = 'DETECT_LOCATION_BY_IP_SUCCESS';
export const DETECT_LOCATION_BY_IP_FAILED = 'DETECT_LOCATION_BY_IP_FAILED';
