export const SAVE_LOCATION = 'SAVE_LOCATION';

export const GET_LOCATION = 'GET_LOCATION';
export const GET_LOCATION_FAILED = 'GET_LOCATION_FAILED';

export const DETECT_LOCATION_BY_DEVICE_POSITION = 'DETECT_LOCATION_BY_DEVICE_POSITION';
export const DETECT_LOCATION_BY_DEVICE_POSITION_SUCCESS =
  'DETECT_LOCATION_BY_DEVICE_POSITION_SUCCESS';
export const DETECT_LOCATION_BY_DEVICE_POSITION_FAILED =
  'DETECT_LOCATION_BY_DEVICE_POSITION_FAILED';
