//loaders./hubList
export const HUBS_LIST_ENABLE_LOADER = 'HUBS_ENABLE_LOADER';
export const HUBS_LIST_DISABLE_LOADER = 'HUBS_DISABLE_LOADER';

//hubs
export const SET_CURRENT_HUB = 'SET_CURRENT_HUB';
export const SET_CURRENT_HUB_SUCCESS = 'SET_CURRENT_HUB_SUCCESS';
export const GET_HUBS_LIST = 'GET_HUBS_LIST';
export const GET_HUBS_LIST_REQUEST = 'GET_HUBS_LIST_REQUEST';
export const GET_HUBS_LIST_SUCCESS = 'GET_HUBS_LIST_SUCCESS';
export const GET_HUBS_LIST_FAILED = 'GET_HUBS_LIST_FAILED';
